name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # - name: Verify dependencies
      #   run: go mod verify

      # - name: Build
      #   shell: bash
      #   run: |
      #     go test -race ./...
      #     go build -v ./cmd/gh

      - name: Run golangci-lint
        uses: docker://golangci/golangci-lint:v1.24-alpine
        with:
          args: run
